{
  config,
  lib,
  pkgs,
  ...
}:
with lib; let
  cfg = config.modules.services.observability-agent;

  # Build the full labels attrset (statics + user extras) so we can
  # render them as a single block — avoids trailing-comma footguns
  # when extraLabels is empty.
  journalLabels =
    {
      job = "systemd-journal";
      host = config.networking.hostName;
    }
    // cfg.loki.extraLabels;

  # Inlined onto one line to sidestep indented-string whitespace
  # stripping. River accepts `labels = { k = "v", k2 = "v2" }` and the
  # one-liner stays readable for the handful of labels we need.
  renderLabels = labels:
    concatStringsSep ", " (
      mapAttrsToList (k: v: ''${k} = "${v}"'') labels
    );

  # Alloy uses River, an HCL-like DSL — not JSON-compatible, so we
  # template it as a string. Keep this config narrow: journald → Loki
  # only. Anything else (file logs, OTel, prometheus.scrape) belongs
  # in a follow-up extension or a per-host override.
  #
  # The relabel rules are passed via `relabel_rules` on the journal
  # source rather than a downstream `loki.relabel` component, because
  # `loki.source.journal` applies relabeling *internally* (see
  # tailer.go: relabel.Process(entryLabels, relabelConfig)) and strips
  # `__journal_*` labels before forwarding. A downstream `loki.relabel`
  # never sees them, so rules placed there silently produce empty
  # values.
  alloyConfig = pkgs.writeText "alloy-config.alloy" ''
    // Auto-generated by modules.services.observability-agent. Do not edit.

    discovery.relabel "journal" {
      targets = []

      rule {
        source_labels = ["__journal__systemd_unit"]
        target_label  = "unit"
      }
      rule {
        source_labels = ["__journal_priority_keyword"]
        target_label  = "level"
      }
    }

    loki.write "default" {
      endpoint {
        url = "${cfg.loki.url}/loki/api/v1/push"
      }
    }

    loki.source.journal "system" {
      forward_to    = [loki.write.default.receiver]
      relabel_rules = discovery.relabel.journal.rules
      max_age       = "${cfg.loki.maxAge}"
      labels        = { ${renderLabels journalLabels} }
    }
  '';
in {
  options.modules.services.observability-agent = {
    enable = mkEnableOption "observability agent (host metrics + log shipping)";

    loki = {
      enable = mkOption {
        description = "Ship the systemd journal to Loki via Grafana Alloy.";
        type = types.bool;
        default = true;
      };

      url = mkOption {
        description = ''
          Loki base URL (no path). Push endpoint is derived as
          ''${url}/loki/api/v1/push.
        '';
        type = types.str;
        # TODO avoid hard-coding atlas
        default = "http://atlas.lan:3100";
      };

      maxAge = mkOption {
        description = ''
          Maximum age of journal entries to ship on first start.
          Caps the backfill so enabling on a host with months of
          existing journal doesn't replay everything into Loki at
          once.
        '';
        type = types.str;
        default = "12h";
      };

      extraLabels = mkOption {
        description = ''
          Static labels added to every journal stream from this host,
          on top of the always-present `job` and `host`.
        '';
        type = types.attrsOf types.str;
        default = {};
        example = literalExpression ''{ env = "prod"; role = "media"; }'';
      };
    };

    prometheus = {
      enable = mkOption {
        description = "Expose host metrics via node_exporter for atlas's Prometheus to scrape.";
        type = types.bool;
        default = true;
      };

      port = mkOption {
        description = "Port node_exporter listens on.";
        type = types.port;
        default = 9100;
      };

      openFirewall = mkOption {
        description = ''
          Open the node_exporter port in the host firewall so Prometheus
          on atlas can scrape over the LAN. The allow is scoped to
          `interface`, which must be set alongside this. Leave false if
          you'd rather gate access via WireGuard / netbird interface
          allows or any other firewall narrowing.
        '';
        type = types.bool;
        default = false;
      };

      interface = mkOption {
        description = ''
          Interface the firewall allow is scoped to. Required when
          openFirewall is set — an unscoped rule would expose the
          exporter on every interface, including WAN-facing ones.
        '';
        type = types.nullOr types.str;
        default = null;
        example = "end0";
      };

      enabledCollectors = mkOption {
        description = "node_exporter collectors to enable beyond the upstream defaults.";
        type = types.listOf types.str;
        default = ["systemd" "processes"];
      };

      disabledCollectors = mkOption {
        description = "node_exporter collectors to explicitly disable.";
        type = types.listOf types.str;
        default = [];
      };
    };
  };

  config = mkIf cfg.enable (mkMerge [
    (mkIf cfg.prometheus.enable {
      services.prometheus.exporters.node = {
        enable = true;
        inherit (cfg.prometheus) port enabledCollectors disabledCollectors;
      };

      # Deliberately NOT forwarding openFirewall upstream: the exporter
      # module's rule is unscoped (all interfaces, both address families),
      # which leaks the port out WAN-facing NICs. Scope to the declared
      # interface like the repo's other serving modules.
      networking.firewall.interfaces = mkIf (cfg.prometheus.openFirewall && cfg.prometheus.interface != null) {
        ${cfg.prometheus.interface}.allowedTCPPorts = [cfg.prometheus.port];
      };

      assertions = [
        {
          assertion = cfg.prometheus.openFirewall -> cfg.prometheus.interface != null;
          message = "modules.services.observability-agent: prometheus.openFirewall = true requires prometheus.interface (an unscoped firewall rule would open the port on every interface).";
        }
      ];
    })

    (mkIf cfg.loki.enable {
      # The upstream NixOS alloy module already adds systemd-journal
      # to SupplementaryGroups for journal access — no extra wiring
      # needed here.
      services.alloy = {
        enable = true;
        configPath = alloyConfig;
      };
    })
  ]);
}
