{
  config,
  lib,
  pkgs,
  ...
}:
with lib; let
  cfg = config.modules.services.observability-agent;

  # Build the full labels attrset (statics + user extras) so we can
  # render them as a single block — avoids trailing-comma footguns
  # when extraLabels is empty.
  journalLabels =
    {
      job = "systemd-journal";
      host = config.networking.hostName;
    }
    // cfg.loki.extraLabels;

  # Inlined onto one line to sidestep indented-string whitespace
  # stripping. River accepts `labels = { k = "v", k2 = "v2" }` and the
  # one-liner stays readable for the handful of labels we need.
  renderLabels = labels:
    concatStringsSep ", " (
      mapAttrsToList (k: v: ''${k} = "${v}"'') labels
    );

  # Alloy uses River, an HCL-like DSL — not JSON-compatible, so we
  # template it as a string. Keep this config narrow: journald → Loki
  # only. Anything else (file logs, OTel, prometheus.scrape) belongs
  # in a follow-up extension or a per-host override.
  alloyConfig = pkgs.writeText "alloy-config.alloy" ''
    // Auto-generated by modules.services.observability-agent. Do not edit.

    loki.write "default" {
      endpoint {
        url = "${cfg.loki.url}/loki/api/v1/push"
      }
    }

    loki.relabel "journal" {
      forward_to = [loki.write.default.receiver]

      rule {
        source_labels = ["__journal__systemd_unit"]
        target_label  = "unit"
      }
      rule {
        source_labels = ["__journal__hostname"]
        target_label  = "hostname"
      }
      rule {
        source_labels = ["__journal_priority_keyword"]
        target_label  = "level"
      }
    }

    loki.source.journal "system" {
      forward_to = [loki.relabel.journal.receiver]
      max_age    = "${cfg.loki.maxAge}"
      labels     = { ${renderLabels journalLabels} }
    }
  '';
in {
  options.modules.services.observability-agent = {
    enable = mkEnableOption "observability agent (host metrics + log shipping)";

    loki = {
      enable = mkOption {
        description = "Ship the systemd journal to Loki via Grafana Alloy.";
        type = types.bool;
        default = true;
      };

      url = mkOption {
        description = ''
          Loki base URL (no path). Push endpoint is derived as
          ''${url}/loki/api/v1/push.
        '';
        type = types.str;
        # TODO avoid hard-coding atlas
        default = "http://atlas.lan:3100";
      };

      maxAge = mkOption {
        description = ''
          Maximum age of journal entries to ship on first start.
          Caps the backfill so enabling on a host with months of
          existing journal doesn't replay everything into Loki at
          once.
        '';
        type = types.str;
        default = "12h";
      };

      extraLabels = mkOption {
        description = ''
          Static labels added to every journal stream from this host,
          on top of the always-present `job` and `host`.
        '';
        type = types.attrsOf types.str;
        default = {};
        example = literalExpression ''{ env = "prod"; role = "media"; }'';
      };
    };

    prometheus = {
      enable = mkOption {
        description = "Expose host metrics via node_exporter for atlas's Prometheus to scrape.";
        type = types.bool;
        default = true;
      };

      port = mkOption {
        description = "Port node_exporter listens on.";
        type = types.port;
        default = 9100;
      };

      openFirewall = mkOption {
        description = ''
          Open the node_exporter port in the host firewall so Prometheus
          on atlas can scrape over the LAN. Leave false if you'd rather
          gate access via WireGuard / netbird interface allows or any
          other firewall narrowing.
        '';
        type = types.bool;
        default = false;
      };

      enabledCollectors = mkOption {
        description = "node_exporter collectors to enable beyond the upstream defaults.";
        type = types.listOf types.str;
        default = ["systemd" "processes"];
      };

      disabledCollectors = mkOption {
        description = "node_exporter collectors to explicitly disable.";
        type = types.listOf types.str;
        default = [];
      };
    };
  };

  config = mkIf cfg.enable (mkMerge [
    (mkIf cfg.prometheus.enable {
      services.prometheus.exporters.node = {
        enable = true;
        inherit (cfg.prometheus) port enabledCollectors disabledCollectors openFirewall;
      };
    })

    (mkIf cfg.loki.enable {
      # The upstream NixOS alloy module already adds systemd-journal
      # to SupplementaryGroups for journal access — no extra wiring
      # needed here.
      services.alloy = {
        enable = true;
        configPath = alloyConfig;
      };
    })
  ]);
}
