# custom doom-city-lights theme
colors:
  primary:
    background: '#1D252C'
    foreground: '#A0B3C5'

  cursor:
    text:   '#41505E'
    cursor: '#9CAABB'

  normal:
    black:   '#10151C'
    red:     '#D95468'
    green:   '#8BD49C'
    yellow:  '#EBBF83'
    blue:    '#5EC4FF'
    magenta: '#E27E8D'
    cyan:    '#70E1E8'
    white:   '#d3d3d3'

  bright:
    black:   '#171D22'
    red:     '#E27E8D'
    green:   '#33CED8'
    yellow:  '#EBBF83'
    blue:    '#5EC4FF'
    magenta: '#B62D65'
    cyan:    '#70E1E8'
    white:   '#728CA0'


# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: Hack Nerd Font
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: Hack Nerd Font
    # Style can be specified to pick a specific face.
    # style: Bold

  # The italic font face
  italic:
    family: Hack Nerd Font
    # Style can be specified to pick a specific face.
    # style: Italic
