# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "mpt3sas" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/data/books" =
    { device = "data/books";
      fsType = "zfs";
    };

  fileSystems."/data/movies" =
    { device = "data/movies";
      fsType = "zfs";
    };

  fileSystems."/data/tv" =
    { device = "data/tv";
      fsType = "zfs";
    };

  fileSystems."/data/files" =
    { device = "data/files";
      fsType = "zfs";
    };

  fileSystems."/data/games" =
    { device = "data/games";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/113F-0AA3";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/" =
    { device = "system/root";
      fsType = "zfs";
    };

  fileSystems."/docker/config" =
    { device = "system/docker/config";
      fsType = "zfs";
    };

  fileSystems."/docker/downloads" =
    { device = "system/docker/downloads";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "system/home";
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "system/var";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "system/nix";
      fsType = "zfs";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
