#! /bin/sh

sxhkd &
 
# Set the background wallpaper
#$HOME/.config/scripts/random-wallpaper.sh &
 
# Launch polybar
$HOME/.config/polybar/launch.sh &
 
# Change X shaped default cursor
xsetroot -cursor_name left_ptr

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        00
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs desktop='^2' state=tiled locked=on
