forgejo-runner:
    token: ENC[AES256_GCM,data:iFrQpP7YbaJIeBtgzVeInQunzbGXuwpkTpa1D2jCdLSbIPC0OyBimA==,iv:CKNsPKPbdpLqH2bD3Ejd/8FCveQl/5YI01VN6i8B10I=,tag:o84VgJmQ40EujmR65kPSIg==,type:str]
codeberg-runner:
    token: ENC[AES256_GCM,data:cuTWo1rhIlDqR/0JXSPcg7jNWnBbrtQ9MujfeasuoKh9GzcavX7MAw==,iv:cq71PLTsSFs76GApvT9MP3Li//xW/w40AMItSmbU7b8=,tag:ON3fdo4pw3WVgqUBxIULWw==,type:str]
sops:
    age:
        - recipient: age1t5e40x0tm32lsyzexm40t6k5t92y9mcpwgvpwg9zmxd7llkayc4srcxu8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdDlraVNDT09QbitXeGJp
            NG5PTjlvZnlhbzhqQ09iYXJBOVlPQTB1UzFvCjVPMks1YlFlb041MmI0eHFld2c0
            MjZLTGEydlVSUnlBK1lFcS9PcVV2TjgKLS0tIEd2OXQxdU9ySHlGZmdxSi83UXp4
            Ykx5cVEzYkhPZ3hJQzZrZXhLQm02U2cKbs1zQnNhx3VTLQsRqF+r4SctfVWXkqmI
            iwxEYqOph5IKeBLVDPVQ7MiETwW/iUmvwqYK2sJBoSIO3Dqw2Ov2Aw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s47fq2kj0qwe9zcuq2czcfjlhvneuutjzjjzx7exjqmqru6j5csqk9pu5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQlZMM3kvN3RWUHI5T2pv
            bWpJc3R0bGVQNTZ3SElFdzJXQ0t2UGRMbDBZCkw2S3ZzcHBlSkZNN0YrVnMyRngr
            NXQyZDJRaURocytFZStJeCtoZ3RwamsKLS0tIDBWdUN5OWdMdi9jMGlHdEd4Ukk2
            V0hMMFZSM3VIMW9ZcTgvUTF4ekVSbkUKNyhv4s1jIVqrxZNBt2yVHCvQwj+mFodO
            kzFAWBPGuB7mvPBqwhGSeSBh78F4Ty9tdUTvSMlG9YhEjs0naeQKmA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jgct0ryhmy8lrqxq4rfhcjmp563tfar2vzpp9etx0sh0ff3kud7srvelpt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacFFsYmR3YUpEdTdSeXdN
            dkF6NW0zVEVnNEtJWWEwTG5DZzJSQ1JnUVhvCmg2QmgzRGs2K25xbDcvNFdSaXhS
            ZnJ3anVKaitLOTlSYjJuR0I3T1hFRFUKLS0tIE5neVlHWnhiZ1pBSEFoK0xXQVRw
            Ly9uUzFWNnNMeFh3MDJrZkZNSGlneWsKB3wQ7hGSL1jyDiDk16ygb9v+XF4Ff6cd
            FbvZrVg3msV361GOVEwkn4eB/iPp5j9RJJ0sG5L/VFziV6T029eBLA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zpelh87c8ccykupspz5uqt0ya0u0cd4tlzzrz92hmwknrlxyn32quqhckc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4emtTR29tSElZNXNlVWR4
            VHdmV2pyTEtzUTFDNWo0dm5sQUJYNzNEeDN3CnJHNG0vSzR1MkVnZjVrMEVCRHU3
            S2x4bmFlTUhSR0NMcDRoUkovcDFWeDgKLS0tIDl2ZXVOaUNqdlNyNklLczN3QXdH
            c2RiUGRaQ3h2VmQ5VTU4VUdGN2pSdG8KYmftPgIwlqJ4FQEHd5eD4Yib5n2/hjda
            r9jat2c91bqLPjKhSd6hOk8LwYeV/g4ZAPFeDBbrfJwnlVjvMgHehQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T17:53:34Z"
    mac: ENC[AES256_GCM,data:eaCXPzVD9HQVXd7MGK21qHkjxxj0Bi12p11fub8U6hckMgu8ElDxTdA7ytJPeZyXQAQxv/IZDzrpvSQNKExRb0fscv0bh1GE/WAF0P/nxqEQZtXoTINaGQGgrSGkGLKW/BCKwJy9dPykVPRg00lKXiELkYsLdqqSk88iUCi2fU8=,iv:cJXdP4JRzxmnRcGVqSGbRsYi98vR5rHS0X7pnvcafNA=,tag:AD/P72HBjLvC0ux+qDfwgg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
