forgejo-runner:
    token: ENC[AES256_GCM,data:nbVBL9G4aDHdTNmNqwfEs5I0Jz/NcroafQWlZc7/aPXalrnQkx7PeA==,iv:Omsm+upn7pylyb8Tc7Dvc50Lw9JJ4JfknFH01sbdUXg=,tag:Dzm5QzC99rDPhZ9raJwzcw==,type:str]
codeberg-runner:
    token: ENC[AES256_GCM,data:KLBijIuMaDLJRD2gkKWreMMXyA113LeBO+U6X/M1MOdYSS/E3n8DKg==,iv:GbsL5qAUbAdehgl55l0Cm2e9Q6H4FW4pVLAi2ixwvUM=,tag:JSZKCMj72lodvs1RNw0REw==,type:str]
nix-cache: ENC[AES256_GCM,data:78Ie2ZVl/e/dqTacDcBfRBR8bV/72AKT9fCDO3mSU3Jw/4mdzzHz8IENr8QmcpVuGe+mELh3X/QHTYqUKs0bNE4uSB6PTJU3Iymd3ffgeaK5t7VGwRJiWlOIVg/uEoJt48iyYDu90wpW,iv:emN5X+mCOKBAjDFeAxpulQHLUAqYkcL+PYRytablO98=,tag:9pa0MawHTw8ITkXNuWWvBA==,type:str]
netbird:
    setup-key: ENC[AES256_GCM,data:i7FY4mGS6tXEjAw5ctTx3CmKhj//QhQNblL6J2N7CQFRjZfy,iv:MBNQ4DhZ9ONG0nCKxJJ0xTa1QmD5YlV93WjNCdoTTYs=,tag:uF4IFK2nVVFAcuXIBl0Z8w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocFBQcWlhNVJkbVdRTU91
            VndZS0JVYjZSUllBeFQzZFQ4cUhoNkt0M1FrCll1Q3U3RVJTWWJnSXpkdVhaVCs5
            RHd4NEpoNFZJaksvdUsxQWxIWDdsL1EKLS0tIE1BOXFHUEpOZFB2UmsvR3pmak1J
            YjM4Zm5PWTg2bGREbm1ibmxibHN6TlkKLXFYq/3qX6k7H/wAG7thJz52mN/VjZI8
            zECkMj1W6fddj66VVT1WBdoYDsIr0oB8IeI6AKUwVeNsjiYCgxdBBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t5e40x0tm32lsyzexm40t6k5t92y9mcpwgvpwg9zmxd7llkayc4srcxu8d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwN0FVSG9LOE5MK2VSK00r
            emgybFlmSzJVMnlueGF3RzRHbzJpTjloaHdjCndmb3BCVzJjMEpyeklibHRKU25E
            TjNJYzAzMzZlNWJCcFZjWlpFVzVheU0KLS0tIElGTTRoSEJucW1qSzdBU01Gemxa
            ZWVRVzlGaGpSVzN2RnJXYW1lSjdoMjAKtuMke3BvFz3EPG/czirkxW+C/hsB07eD
            Qh6ix/j9DXsqYMvP8REqySR5XmuLltji2CbvY3QhjutNfEwWaZ+ArQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s47fq2kj0qwe9zcuq2czcfjlhvneuutjzjjzx7exjqmqru6j5csqk9pu5e
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcjFuNm12SUVxQk53YlhQ
            YS84VEtEWDJiWnJORno2MW8wV3RBQjZmSFJzCkVvUTc2N0UvdXlzbi83bDR0bE4r
            ZCswYXFuOThFSWt3bGV1T2s1blI5Y1UKLS0tIGZjOHJDSy8wMXhTTVo0RXM4MXRU
            MFJjYUhSQXpKVVM5RXVTUTZwekhaeUkKsyAae9bixp6j0jRvVBNiFWHjwZwjB7dT
            /jMaesRC7R3XoYI2pnAi60JUrXuKzyxyyjtSeJ0GS4QyiRR25BhCbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jgct0ryhmy8lrqxq4rfhcjmp563tfar2vzpp9etx0sh0ff3kud7srvelpt
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNT2NUZ3Vvc3h0akFQZ2hF
            eTEvZ0w3bWJJN1dDcHlyYnE5ZHZjY29wS1VrCm14WDVPS2crdUNYcHJ3NlE5a0hI
            N1BraW95QVlZd2VVU3ZNN1pjMFp5MmcKLS0tIENPSUtzaDZHMXh4a29VZEdrZVcv
            blNodHBJREw4Sk5jQTh3akw1Yk1PWnMKTIJzh0QHDLKB0U51St2HU/ESNnNgYGzL
            4n661P5h8Sy9MYFossBn323ZRSZ4HP2hzCUGSrldoty9vhdOC0WuPg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zpelh87c8ccykupspz5uqt0ya0u0cd4tlzzrz92hmwknrlxyn32quqhckc
    lastmodified: "2026-05-26T17:26:20Z"
    mac: ENC[AES256_GCM,data:6BjMln24I4bDzgi8Rpjr+NUJEJQXLzKjLuhED0BD5md3ij77HqLe/77aExLTBUq78r4oPt8m6JoVikWedehBrAI0J+mC01hZkyjfPgLC0vZc9EhVV2/QvJ7N5Yx1qKrFncU+X2jXZKGdbpclMWYIOB6kfsxVqv+ED4Av2fBvnBw=,iv:QYo3PE6s9UNh6652BlXiEUVsqVJxwafT/aWLSCTV5iU=,tag:dMe+onem3e0VqicRs0zCdQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
