forgejo-runner:
    token: ENC[AES256_GCM,data:LEPHuXMZ6GJo7e5CtgmG9Zc3msJD15CXCRG9qLoPlMFXIrf4hEQiPg==,iv:npkbjsMTCsopcNpARcuglCOqg8xOihfVsX3jLPpMpK8=,tag:Jy2/2iwhXuArcMDg+cflvA==,type:str]
nix-cache: ENC[AES256_GCM,data:OXQ9HjyymDS06nAxqasB/iyWS3pZP1N+4mNYhRMzSyA0QQCesMeTiMkQq8CBLZm/GZe3RfG7wj7ckoSXtBlnvDMpOuBUUfejYcwkrGEWWH7GlDu12VRlmgfFikvvApu0SPF34IJqOA5q,iv:qxr5rfZfhBoR/DBRA5sLzjeuHS9eWo9uoAYLrBMmg74=,tag:t6rS+oyrSmpHmPxCIte9JA==,type:str]
netbird:
    setup-key: ENC[AES256_GCM,data:SxWI06sSlGHBNEKnAFrwMGeushZzoL1FVdBMM+ahppcz/H/v,iv:nVuL83iQ0e9kds88iSexaErra7d/LTttHspqUEQF5QA=,tag:V/OfND2zfY/q7qrbikG3sw==,type:str]
github-runner:
    token: ENC[AES256_GCM,data:bz2gLM4ylkccS9uK77EmTfKLYL6lBuIRR7QOroBLWPbQXC2tODsWE0zyx8SkPoDEIyeTl9xkTC/GdC6V5ngFG5rrmTfnhvW7mLM0yAjXs4IfG4lgvBugsSqTIeta,iv:Xv8eJhwPKc1QF+/Jo44pNWtDTxwpLhprZd3aXLW2sr4=,tag:JoriSzo1U76f1vuGhHxlrw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRGNLdm05NHhGSGJBRm9U
            Vmw2YWVnRU5lWGVpTnIwakJhaWZQcWVHUDNNCkV5L0p0cFkrVkhYOTI3ckdlek1K
            MGZuYkQyNktqR3hvUUV1eklsUnFQb1kKLS0tIGdrUVJZU2JkUS8yM25hRFJ1SlhL
            bmFqbnhQL2tZOUR6K1VNcUNtclY5S2cKz8aNqTmzS4N/1ybmWepvCjDWdv5mkpe/
            NC1kqILS9GGPVLMqYEKYTA+1VKk3YL6be21w5pKwSM+zQSitZJKPFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t5e40x0tm32lsyzexm40t6k5t92y9mcpwgvpwg9zmxd7llkayc4srcxu8d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5a2piR1R0K2lYdFBSZWdT
            K3ZMTlRlOG9GekhxdUZheXJrRk4vWFo3WXpzCmtrK0VkVU5RV3BDTTQzWDRXbjRU
            OXl0L0kzZUhLMlRmMVBVczlhanZqdTQKLS0tIG5XQUlpQW53bGFWTGYva2hrNElK
            RHNRMGhRV0lMclNLdlEranFJL2JJZ3cKB+/sdgGx7kJz2bI7zEyUWsMA7LeeLq0Z
            yupVC042Fg2h6F5mlaj8jrH5wcPUkQSXUczoS4Cngr8tqVjeAAKbPg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s47fq2kj0qwe9zcuq2czcfjlhvneuutjzjjzx7exjqmqru6j5csqk9pu5e
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbW9mTnIvWWFTT2dobTBh
            LzNxbGpnTTcwVFBQRy9idTViZEk4ZFFBSWtVCk5vZW5QVThwYUhvdndGM3dFTWdq
            OEJGY2JQaGlDUktzRUxDVGNoRDkvM3cKLS0tIEhDb3lJNHBpRjg1Z0JBY2xKSWZw
            UGZXYTJ3dEU4MlQ0TnRCMDRUWkVNbHMKVD7KX6Rnvp3Dw6yG/crV+8PQ4vVvduWS
            4GYfDEN67/UxXFbOaQg0/KlpfSp9/MYJjA7icGi6qW3+1ELqBHNblw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jgct0ryhmy8lrqxq4rfhcjmp563tfar2vzpp9etx0sh0ff3kud7srvelpt
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZURLOTA2MG9WU2hmakla
            YUd1dXVPcGNLVHFpR2RjNktWcExSRHRwNVhzClYwa3dpaDdWZExhNk84a0U1enAy
            aXZRU3ZhaVBCUWJhU09QVEpqdlJ5dnMKLS0tIEwrTG1wa0xFdkEzU3BXeTVzcmZK
            alRpc0Uyb0h1MlVMbm11NFJES2ZMYmMKw16stk58PNe8yQ57yyA2bOfYVQcTAtde
            pbhfcu3t7LHL13YucbbicIMK8kNQ7QgERNON9TLTIOc3b0cUXiBulQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zpelh87c8ccykupspz5uqt0ya0u0cd4tlzzrz92hmwknrlxyn32quqhckc
    lastmodified: "2026-08-11T20:23:34Z"
    mac: ENC[AES256_GCM,data:qlGJs9xRjp1OGig4AZxYDWUOzu0RMQ7XwPI1fQ/xQxQ5o0qzhYCpdhBGeEfz4Hx/8DnmaQFVnEs4x1aYYWWq2N3naxvLr3TOPTRxdJyD/psrAAO/6pnLGweURx23NAsp/GY0ermjYGtYsCRGja4tdzsHVF52RnHrT+Y/Hz2Fqf0=,iv:9dYPDOCQ5NBgJgx13O6aGW8eY5NayN0lTOxzAAmnWmQ=,tag:sm3jyL2RdKXUHIWbvG6oFg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
