#! /bin/sh

wmname LG3D

sxhkd &
 
# Set the background wallpaper
#$HOME/.config/scripts/random-wallpaper.sh &
 
# Launch ntfd, which polybar depends on 
# Launch polybar
$HOME/.config/polybar/scripts/launch.sh &
 
# Change X shaped default cursor
xsetroot -cursor_name left_ptr

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        00
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "Firefox Developer Edition" desktop='^1' state=tiled focus=on
bspc rule -a Emacs                   desktop='^2' state=tiled locked=on focus=on
bspc rule -a kitty                   desktop='^3' state=tiled focus=on
bspc rule -a discord                 desktop='^4' state=tiled
bspc rule -a TelegramDesktop         desktop='^4' state=tiled

bspc config external_rules_command ~/.config/bspwm/scripts/external_rules.sh
