name: "Build Hosts"
on:
  schedule:
    - cron: '0 3 * * 1'
jobs:
  build-hyperion:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: hyperion
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#nixosConfigurations.hyperion.config.system.build.toplevel
    - run: nix build .#nixosConfigurations.atlas.config.system.build.toplevel
    - run: nix shell --command sh -c "echo OK"
