(package "emacs-lisp"
         "1.0.0"
         "")

(website-url "")
(keywords "")

(package-file "emacs-lisp.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")

(depends-on "emacs" "26.1")
