{
  imports = [
    ./airvpn
    ./bandcamp-import
    ./cachix
    ./desktop
    ./docker-socket-proxy
    ./extract-embedded-subs
    ./github-runner
    ./hardware
    ./keepalived
    ./netbird
    ./nfs
    ./nix-cache
    ./observability-agent
    ./ollama
    ./printing
    ./samba
    ./sudo-rs
    ./syncthing
    ./systemd
    ./yubikey
    ./zfs
  ];
}
