name: Update Nix flake

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

defaults:
  run:
    shell: nu {0}

jobs:
  update-nixos-unstable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hustcer/setup-nu@main
        with:
          version: "0.106.1"
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run nix flake update
        run: |
          let output = ^mktemp
          nix flake update
            | complete
            | get stdout
            | save -f $output

          $"UPDATE_OUTPUT_FILE=($output)" | save --append $env.GITHUB_ENV
      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: master
          BRANCH_DATE_FORMAT: %Y%m%d%H%M%S
        run: |
          let date_str = date now | date into-timezone UTC | format date $env.BRANCH_DATE_FORMAT
          let branch_name = $"update-nix-flake-($date_str)"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git checkout -b $branch_name
          git add flake.lock
          git commit -m "Flake bump"
          git push -u origin $branch_name

          let pr_body = open $env.UPDATE_OUTPUT_FILE

          gh pr create --title $"Flake bump ($date_str)" --body $pr_body --base $env.DEFAULT_BRANCH --head $branch_name
