name: Update Nix flake

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

defaults:
  run:
    shell: nu {0}

jobs:
  update-nixos-unstable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hustcer/setup-nu@main
        with:
          version: "0.106.1"
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run nix flake update
        run: "nu .github/workflows/scripts/update-nix-flake.nu"
      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          BRANCH_DATE_FORMAT: "%Y%m%d%H%M%S"
        run: "nu .github/workflows/scripts/commit-and-push.nu"
