{
  config,
  lib,
  pkgs,
  ...
}:
with lib; let
  cfg = config.modules.linux.oci.services.caddy;
  ociLib = config.modules.linux.oci.lib;
  imageLib = import ./lib.nix {inherit lib;};

  # Generate a Caddyfile from configuration
  generateCaddyfile = let
    # Generate a reverse proxy block
    mkProxyBlock = name: proxy: let
      hosts = concatStringsSep ",\n" (map (h: "${proxy.scheme}://${h}") proxy.hosts);
    in ''
      ${hosts} {
        reverse_proxy ${proxy.upstream}
      }
    '';

    # Generate a file server block
    mkFileServerBlock = name: site: let
      hosts = concatStringsSep ",\n" (map (h: "${site.scheme}://${h}") site.hosts);
    in ''
      ${hosts} {
        root * ${site.root}
        file_server
      }
    '';

    proxyBlocks = concatStringsSep "\n" (mapAttrsToList mkProxyBlock cfg.reverseProxies);
    fileServerBlocks = concatStringsSep "\n" (mapAttrsToList mkFileServerBlock cfg.fileServers);
    extraConfig = optionalString (cfg.extraConfig != "") cfg.extraConfig;
  in ''
    # Generated by NixOS OCI Caddy module
    ${cfg.globalConfig}

    ${proxyBlocks}
    ${fileServerBlocks}
    ${extraConfig}
  '';

  # Generate an index.html listing all services
  generateIndexHtml = let
    proxyRows = concatStringsSep "\n" (mapAttrsToList (name: proxy: ''
      <tr>
        <td>${proxy.displayName}</td>
        <td><a href="${proxy.scheme}://${head proxy.hosts}">${head proxy.hosts}</a></td>
      </tr>
    '') (filterAttrs (_: p: p.showInIndex) cfg.reverseProxies));
  in ''
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>${cfg.index.title}</title>
        <style>
          body { font-family: system-ui, sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; }
          table { border-collapse: collapse; width: 100%; }
          th, td { text-align: left; padding: 0.5rem; border-bottom: 1px solid #ddd; }
          th { background: #f5f5f5; }
          a { color: #0066cc; }
        </style>
      </head>
      <body>
        <h1>${cfg.index.title}</h1>
        <p>${cfg.index.description}</p>
        <table>
          <thead>
            <tr>
              <th>Service</th>
              <th>URL</th>
            </tr>
          </thead>
          <tbody>
            ${proxyRows}
          </tbody>
        </table>
      </body>
    </html>
  '';

  # Build a real directory in the Nix store for the index page,
  # so it can be bind-mounted into the container without broken symlinks.
  indexDir = pkgs.writeTextDir "index.html" generateIndexHtml;

  # Reverse proxy option type
  reverseProxyOpts = {name, ...}: {
    options = {
      hosts = mkOption {
        type = types.listOf types.str;
        description = "List of hostnames for this proxy (e.g., ['radarr.home.lan'])";
        example = ["radarr.home.lan" "radarr.example.com"];
      };

      upstream = mkOption {
        type = types.str;
        description = "Upstream address (e.g., '192.168.0.3:7878')";
        example = "192.168.0.3:7878";
      };

      scheme = mkOption {
        type = types.enum ["http" "https"];
        default = "http";
        description = "URL scheme for the frontend";
      };

      displayName = mkOption {
        type = types.str;
        default = name;
        description = "Human-readable name for index page";
      };

      showInIndex = mkOption {
        type = types.bool;
        default = true;
        description = "Whether to show this service in the auto-generated index page";
      };
    };
  };

  # File server option type
  fileServerOpts = {name, ...}: {
    options = {
      hosts = mkOption {
        type = types.listOf types.str;
        description = "List of hostnames for this file server";
        example = ["home.lan"];
      };

      root = mkOption {
        type = types.str;
        description = "Root directory to serve (path inside container)";
        default = "/srv";
      };

      scheme = mkOption {
        type = types.enum ["http" "https"];
        default = "http";
        description = "URL scheme for the frontend";
      };
    };
  };
in {
  options.modules.linux.oci.services.caddy = {
    enable = mkEnableOption "Caddy reverse proxy";

    image = imageLib.mkImageOptions {
      repository = "caddy";
      version = "2-alpine";
    };

    baseDir = mkOption {
      type = types.str;
      description = "Base directory for Caddy data and config persistence";
      example = "/docker/caddy";
    };

    reverseProxies = mkOption {
      type = types.attrsOf (types.submodule reverseProxyOpts);
      default = {};
      description = "Reverse proxy configurations";
      example = literalExpression ''
        {
          radarr = {
            hosts = ["radarr.home.lan"];
            upstream = "192.168.0.3:7878";
          };
          sonarr = {
            hosts = ["sonarr.home.lan"];
            upstream = "192.168.0.3:8989";
          };
        }
      '';
    };

    fileServers = mkOption {
      type = types.attrsOf (types.submodule fileServerOpts);
      default = {};
      description = "Static file server configurations";
    };

    globalConfig = mkOption {
      type = types.lines;
      default = "";
      description = "Global Caddy configuration (placed at top of Caddyfile)";
      example = ''
        {
          admin off
        }
      '';
    };

    extraConfig = mkOption {
      type = types.lines;
      default = "";
      description = "Extra Caddyfile content appended at the end";
    };

    index = {
      enable = mkOption {
        type = types.bool;
        default = false;
        description = "Generate an index.html listing all services";
      };

      hosts = mkOption {
        type = types.listOf types.str;
        default = ["home.lan"];
        description = "Hostnames for the index page";
      };

      title = mkOption {
        type = types.str;
        default = "Service Index";
        description = "Title for the index page";
      };

      description = mkOption {
        type = types.str;
        default = "Available services on the local network";
        description = "Description text for the index page";
      };
    };

    staticDir = mkOption {
      type = types.nullOr types.str;
      default = null;
      description = "Optional host directory to mount as /srv for static files";
    };
  };

  config = mkIf cfg.enable {
    modules.linux.oci._managedPaths.${cfg.baseDir} = {};

    # Add the index file server if enabled
    modules.linux.oci.services.caddy.fileServers = mkIf cfg.index.enable {
      index = {
        hosts = cfg.index.hosts;
        root = "/srv/index";
      };
    };

    # Write the Caddyfile to /etc
    environment.etc."caddy/Caddyfile".text = generateCaddyfile;

    virtualisation.oci-containers.containers."caddy" = {
      image = imageLib.renderImage cfg.image;
      ports = [
        "80:80"
        "443:443"
        "443:443/udp"
      ];
      volumes =
        [
          "/etc/caddy/Caddyfile:/etc/caddy/Caddyfile:ro"
          "${cfg.baseDir}/data:/data"
          "${cfg.baseDir}/config:/config"
        ]
        ++ optional cfg.index.enable "${indexDir}:/srv/index:ro"
        ++ optional (cfg.staticDir != null) "${cfg.staticDir}:/srv/static:ro";
      extraOptions =
        [
          "--cap-add=NET_ADMIN"
          "--network=host"
        ]
        ++ imageLib.mkImageLabels {
          module = "caddy";
          image = cfg.image;
        };
      log-driver = "journald";
    };

    # Caddy uses host networking, wire to root target
    systemd.services."podman-caddy" = {
      # Podman does not create missing bind-mount sources (statfs error at
      # container start); _managedPaths only covers baseDir itself, so its
      # data/config children need creating here.
      serviceConfig.ExecStartPre = ["${pkgs.coreutils}/bin/mkdir -p ${cfg.baseDir}/data ${cfg.baseDir}/config"];
      # Self-heal through transient DNS/registry outages during deploys (e.g.
      # Pi-hole bouncing while caddy pulls a bumped image) rather than hitting
      # the start-limit and staying dead. See mkServiceConfig in default.nix
      # for the full rationale; caddy wires its unit by hand because it uses
      # host networking, so the settings are repeated here.
      startLimitIntervalSec = mkOverride 90 0;
      serviceConfig = {
        Restart = mkOverride 90 "always";
        RestartSec = mkOverride 90 10;
      };
      # Depend on pihole if it's enabled (DNS resolution)
      after = optional config.modules.linux.oci.services.pihole.enable "podman-pihole.service";
      requires = optional config.modules.linux.oci.services.pihole.enable "podman-pihole.service";
      partOf = ["${ociLib.rootTargetName}.target"];
      wantedBy = ["${ociLib.rootTargetName}.target"];
    };
  };
}
