{
  config,
  lib,
  ...
}:
with lib; let
  cfg = config.modules.linux.oci.services.job-ops;
  ociLib = config.modules.linux.oci.lib;
  imageLib = import ./lib.nix {inherit lib;};

  boolEnv = b:
    if b
    then "1"
    else "0";
in {
  options.modules.linux.oci.services.job-ops = {
    enable = mkEnableOption "JobOps — self-hosted job-search pipeline (discovery, fit-scoring, CV tailoring)";

    image = imageLib.mkImageOptions {
      # ghcr publishes the v-prefixed git tag (e.g. v0.9.0); a bare "0.9.0"
      # tag does not exist. Pre-1.0 and very actively developed, so we pin an
      # explicit tag rather than float :latest — auto-update bumps the digest
      # in oci-images.json on each release.
      repository = "ghcr.io/dakheera47/job-ops";
      version = "v0.9.0";
    };

    baseDir = mkOption {
      description = ''
        State directory for JobOps, bind-mounted at the container's DATA_DIR
        (/app/data). Holds the SQLite database (jobs.db), generated PDFs
        (pdfs/), import scratch (imports/) and Cloudflare challenge cookies
        (cloudflare-cookies/). SQLite-backed — no external database.
      '';
      type = types.str;
      example = "/data/apps/job-ops";
    };

    port = mkOption {
      description = "Host port for the JobOps web UI (proxied to container port 3001).";
      type = types.port;
      default = 5627; # J-O-B-S on a phone keypad
    };

    publicBaseUrl = mkOption {
      description = ''
        Public URL where JobOps is reachable. Set as JOBOPS_PUBLIC_BASE_URL so
        tracer links embedded in PDFs generated by background pipeline runs
        (where the request host can't be inferred) resolve correctly.
      '';
      type = types.str;
      example = "https://jobs.3679.space";
    };

    llm = {
      provider = mkOption {
        description = ''
          LLM provider id (LLM_PROVIDER). JobOps scores job fit and ghostwrites
          tailored CVs through this provider. The matching API key (if the
          provider needs one) is read from the sops env file: "openrouter"
          reads OPENROUTER_API_KEY, every other provider reads the universal
          LLM_API_KEY.
        '';
        type = types.enum ["openrouter" "openai" "gemini" "glm" "ollama" "lmstudio" "openai_compatible" "codex" "gemini_cli"];
        default = "openrouter";
      };

      model = mkOption {
        description = ''
          Model slug passed as MODEL. For OpenRouter this is the routed model
          (e.g. "google/gemini-3-flash-preview", "openai/gpt-4.1-mini"). The
          upstream default routes Gemini 3 Flash, which the project reports at
          roughly $12 for 3000+ scored jobs.
        '';
        type = types.str;
        default = "google/gemini-3.7-flash";
      };

      apiKey = {
        enable =
          mkEnableOption "an API key for the LLM provider, read from sops at job-ops/llm-api-key"
          // {default = true;};
      };
    };

    auth = {
      enable = mkOption {
        description = ''
          Enable JobOps' built-in protection. JobOps is FULLY UNAUTHENTICATED
          by default; since this instance is published at publicBaseUrl, leave
          this on. BASIC_AUTH_USER/BASIC_AUTH_PASSWORD seed the first admin
          account on the initial DB migration and gate write actions; JWT_SECRET
          signs session tokens (rendered from sops so sessions survive container
          recreation instead of being regenerated into DATA_DIR).
        '';
        type = types.bool;
        default = true;
      };

      username = mkOption {
        description = "BASIC_AUTH_USER — the seeded admin username (not secret).";
        type = types.str;
        default = "admin";
      };

      jwtExpirySeconds = mkOption {
        description = "JWT_EXPIRY_SECONDS — session-token lifetime.";
        type = types.int;
        default = 86400;
      };
    };

    jobspy = {
      remote = mkOption {
        description = ''
          Default JobSpy (Indeed/LinkedIn/Glassdoor) discovery to remote-only
          via JOBSPY_IS_REMOTE. This is only the fallback default — a per-run
          workplace-type selection in the UI overrides it. Biases the instance
          toward remote roles.
        '';
        type = types.bool;
        default = true;
      };

      countryIndeed = mkOption {
        description = ''
          Default Indeed country targeting (JOBSPY_COUNTRY_INDEED). Fallback
          default only; per-extractor country chosen in the UI overrides it.
        '';
        type = types.str;
        default = "USA";
      };
    };

    adzuna = {
      enable = mkEnableOption ''
        the Adzuna extractor (multi-country job API with US coverage). When
        enabled, requires sops secrets at job-ops/adzuna-app-id and
        job-ops/adzuna-app-key (free Adzuna developer account)
      '';
    };

    gmail = {
      enable = mkEnableOption ''
        Gmail OAuth so JobOps can track recruiter replies in your inbox. When
        enabled, requires sops secrets at job-ops/gmail-client-id and
        job-ops/gmail-client-secret. The OAuth callback defaults to
        <publicBaseUrl>/oauth/gmail/callback
      '';
    };

    rxresume = {
      enable = mkEnableOption ''
        Reactive Resume (RxResume) v5 integration for tailored PDF resume
        generation. When enabled, requires a sops secret at
        job-ops/rxresume-api-key
      '';

      url = mkOption {
        description = "RXRESUME_URL — base URL of the RxResume instance (defaults to the hosted service).";
        type = types.str;
        default = "https://rxresu.me";
      };
    };

    timezone = mkOption {
      description = "TZ env var passed to the container.";
      type = types.str;
      default = "America/New_York";
    };

    networks = mkOption {
      description = ''
        Podman networks the container joins. "default" is sufficient — newt
        (the Pangolin tunnel client) already bridges the default network, so it
        reaches JobOps by its network alias on the container port. No VPN
        egress is needed (job-board scraping is not identifying traffic), so
        this service does not route through gluetun.
      '';
      type = types.listOf types.str;
      default = ["default"];
    };

    dependsOn = mkOption {
      description = "Other oci-containers this container should start after.";
      type = types.listOf types.str;
      default = [];
    };

    extraEnv = mkOption {
      description = "Additional plain (non-secret) env vars passed to the container.";
      type = types.attrsOf types.str;
      default = {};
    };

    configProperties = mkOption {
      description = "ZFS properties applied to baseDir. Defaults tuned for the SQLite workload.";
      type = types.attrsOf types.str;
      default = {recordsize = "64K";};
    };
  };

  config = mkIf cfg.enable {
    modules.linux.oci._managedPaths.${cfg.baseDir}.properties = cfg.configProperties;

    modules.linux.oci.networks = listToAttrs (
      map (n: nameValuePair n {enable = true;}) cfg.networks
    );

    sops.secrets =
      optionalAttrs cfg.llm.apiKey.enable {
        "job-ops/llm-api-key" = {};
      }
      // optionalAttrs cfg.auth.enable {
        "job-ops/basic-auth-password" = {};
        "job-ops/jwt-secret" = {};
      }
      // optionalAttrs cfg.adzuna.enable {
        "job-ops/adzuna-app-id" = {};
        "job-ops/adzuna-app-key" = {};
      }
      // optionalAttrs cfg.gmail.enable {
        "job-ops/gmail-client-id" = {};
        "job-ops/gmail-client-secret" = {};
      }
      // optionalAttrs cfg.rxresume.enable {
        "job-ops/rxresume-api-key" = {};
      };

    # All secret-bearing env is rendered here so values never live in the Nix
    # store. Upstream job-ops only reads two provider-key env vars:
    # OPENROUTER_API_KEY for the openrouter provider, and LLM_API_KEY (a
    # universal slot) for every other provider — there is no per-provider
    # OPENAI_API_KEY/GEMINI_API_KEY/etc. — so the mapping only ever picks
    # between those two. podman performs no $VAR expansion, so the value
    # must be literal.
    sops.templates."job-ops-env".content = let
      providerKeyVar =
        if cfg.llm.provider == "openrouter"
        then "OPENROUTER_API_KEY"
        else "LLM_API_KEY";
    in
      concatStringsSep "\n" (
        optional cfg.llm.apiKey.enable
        "${providerKeyVar}=${config.sops.placeholder."job-ops/llm-api-key"}"
        ++ optionals cfg.auth.enable [
          "BASIC_AUTH_PASSWORD=${config.sops.placeholder."job-ops/basic-auth-password"}"
          "JWT_SECRET=${config.sops.placeholder."job-ops/jwt-secret"}"
        ]
        ++ optionals cfg.adzuna.enable [
          "ADZUNA_APP_ID=${config.sops.placeholder."job-ops/adzuna-app-id"}"
          "ADZUNA_APP_KEY=${config.sops.placeholder."job-ops/adzuna-app-key"}"
        ]
        ++ optionals cfg.gmail.enable [
          "GMAIL_OAUTH_CLIENT_ID=${config.sops.placeholder."job-ops/gmail-client-id"}"
          "GMAIL_OAUTH_CLIENT_SECRET=${config.sops.placeholder."job-ops/gmail-client-secret"}"
        ]
        ++ optional cfg.rxresume.enable
        "RXRESUME_API_KEY=${config.sops.placeholder."job-ops/rxresume-api-key"}"
      )
      + "\n";

    virtualisation.oci-containers.containers.job-ops = {
      image = imageLib.renderImage cfg.image;
      inherit (cfg) dependsOn;
      environment =
        {
          "TZ" = cfg.timezone;
          "LLM_PROVIDER" = cfg.llm.provider;
          "MODEL" = cfg.llm.model;
          "JOBOPS_PUBLIC_BASE_URL" = cfg.publicBaseUrl;
          "JOBSPY_IS_REMOTE" = boolEnv cfg.jobspy.remote;
          "JOBSPY_COUNTRY_INDEED" = cfg.jobspy.countryIndeed;
        }
        // optionalAttrs cfg.auth.enable {
          "BASIC_AUTH_USER" = cfg.auth.username;
          "JWT_EXPIRY_SECONDS" = toString cfg.auth.jwtExpirySeconds;
        }
        // optionalAttrs cfg.gmail.enable {
          "GMAIL_OAUTH_REDIRECT_URI" = "${cfg.publicBaseUrl}/oauth/gmail/callback";
        }
        // optionalAttrs cfg.rxresume.enable {
          "RXRESUME_URL" = cfg.rxresume.url;
        }
        // cfg.extraEnv;
      environmentFiles = [config.sops.templates."job-ops-env".path];
      volumes = [
        "${cfg.baseDir}:/app/data"
      ];
      ports = [
        "${toString cfg.port}:3001"
      ];
      extraOptions =
        [
          "--network-alias=job-ops"
        ]
        ++ (map (n: "--network=${ociLib.networkName n}") cfg.networks)
        ++ imageLib.mkImageLabels {
          module = "job-ops";
          inherit (cfg) image;
        };
      log-driver = "journald";
    };

    systemd.services."podman-job-ops" = ociLib.mkServiceConfig {
      inherit (cfg) networks;
      sopsTemplates = ["job-ops-env"];
    };
  };
}
