{
  config,
  lib,
  pkgs,
  ...
}:
with lib; let
  cfg = config.modules.linux.oci.services.recyclarr;
  ociLib = config.modules.linux.oci.lib;
  imageLib = import ./lib.nix {inherit lib;};

  enabledInstances = {
    # TODO generate yaml more dynamically
    sonarr_main = {
      kind = "sonarr";
      baseUrl = "http://gluetun:8989";
      apiKeySecret = "recyclarr/sonarr-main-api-key";
      body = ''
        quality_definition:
          type: series
      '';
    };
    radarr_main = {
      kind = "radarr";
      baseUrl = "http://gluetun:7878";
      apiKeySecret = "recyclarr/radarr-main-api-key";
      # Guide-backed profiles carry only their own tier formats, so the
      # custom_formats below are additive rather than duplicates — dropping
      # them would silently remove all audio-format scoring. The anime block
      # is the exception: those three are in the guide profile already, and
      # the per-profile score overrides the guide's.
      body = ''
        quality_definition:
          type: movie

        quality_profiles:
          - trash_id: d1d67249d3890e49bc12e275d989a7e9 # HD Bluray + WEB
            reset_unmatched_scores:
              enabled: true
          - trash_id: 64fb5f9858489bdac2af690e27c8f42f # UHD Bluray + WEB
            reset_unmatched_scores:
              enabled: true
          - trash_id: 722b624f9af1e492284c4bc842153a38 # [Anime] Remux-1080p
            reset_unmatched_scores:
              enabled: true

        custom_formats:
          # Movie Versions
          - trash_ids:
              - 570bc9ebecd92723d2d21500f4be314c # Remaster
              - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
              - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
              - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
              - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
              - 957d0f44b592285f26449575e8b1167e # Special Edition
            assign_scores_to:
              - name: HD Bluray + WEB

          # Audio Advanced
          - trash_ids:
              - 496f355514737f7d83bf7aa4d24f8169 # TrueHD ATMOS
              - 2f22d89048b01681dde8afe203bf2e95 # DTS X
              - 417804f7f2c4308c1f4c5d380d4c4475 # ATMOS (undefined)
              - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
              - 3cafb66171b47f226146a0770576870f # TrueHD
              - dcf3ec6938fa32445f590a4da84256cd # DTS-HD MA
              - a570d4a0e56a2874b64e5bfa55202a1b # FLAC
              - e7c2fcae07cbada050a0af3357491d7b # PCM
              - 8e109e50e0a0b83a5098b056e13bf6db # DTS-HD HRA
              - 185f1dd7264c4562b9022d963ac37424 # DD+
              - f9f847ac70a0af62ea4a08280b859636 # DTS-ES
              - 1c1a4c5e823891c75bc50380a6866f73 # DTS
              - 240770601cc226190c367ef59aba7463 # AAC
              - c2998bd0d90ed5621d8df281e839436e # DD
            assign_scores_to:
              - name: UHD Bluray + WEB

          # Movie Versions + SDR
          - trash_ids:
              - 570bc9ebecd92723d2d21500f4be314c # Remaster
              - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
              - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
              - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
              - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
              - 9c38ebb7384dada637be8899efa68e6f # SDR
            assign_scores_to:
              - name: UHD Bluray + WEB

          - trash_ids:
              - 064af5f084a0a24458cc8ecd3220f93f # Uncensored
              - a5d148168c4506b55cf53984107c396e # 10bit
              - 4a3b087eea2ce012fcc1ce319259a3be # Anime Dual Audio
            assign_scores_to:
              - name: "[Anime] Remux-1080p"
                score: 0
      '';
    };
  };

  instancesByKind = kind: filterAttrs (_: i: i.kind == kind) enabledInstances;

  indentBody = body: indent:
    if body == ""
    then ""
    else let
      pad = concatStrings (genList (_: " ") indent);
      lines = splitString "\n" (removeSuffix "\n" body);
      indented = map (l:
        if l == ""
        then ""
        else "${pad}${l}")
      lines;
    in
      concatStringsSep "\n" indented + "\n";

  renderInstance = name: i:
    "  ${name}:\n"
    + "    base_url: ${i.baseUrl}\n"
    + "    api_key: !secret ${name}_api_key\n"
    + (indentBody i.body 4);

  renderKindBlock = kind: let
    instances = instancesByKind kind;
  in
    if instances == {}
    then ""
    else "${kind}:\n" + concatStringsSep "" (mapAttrsToList renderInstance instances);

  recyclarrYamlContent =
    "# Generated by NixOS OCI recyclarr module — do not edit on disk\n"
    + (renderKindBlock "sonarr")
    + (renderKindBlock "radarr")
    + (optionalString (cfg.extraConfig != "") "\n${cfg.extraConfig}\n");

  recyclarrYamlFile =
    pkgs.writeText "recyclarr.yml" recyclarrYamlContent;
in {
  options.modules.linux.oci.services.recyclarr = {
    enable = mkEnableOption "Recyclarr TRaSH-Guides quality profile sync";

    # Upstream publishes no `latest` tag — it is explicitly disabled in their
    # release CI, and their docs direct users to a major-version tag so that
    # breaking majors stay opt-in.
    image = imageLib.mkImageOptions {
      repository = "ghcr.io/recyclarr/recyclarr";
      version = "8";
    };

    baseDir = mkOption {
      description = ''
        Base directory for recyclarr state (mounted at /config). Holds the
        cached TRaSH-Guides repo and run logs. recyclarr.yml and secrets.yml
        are bind-mounted on top of this directory from the nix store /
        sops template paths, so on-disk copies are shadowed.
      '';
      type = types.str;
      example = "/data/apps/recyclarr";
    };

    user = {
      uid = mkOption {
        description = "UID to run the container as.";
        type = types.int;
        default = 1000;
      };
      gid = mkOption {
        description = "GID to run the container as.";
        type = types.int;
        default = 100;
      };
    };

    timezone = mkOption {
      description = "Timezone for the container.";
      type = types.str;
      default = "America/New_York";
    };

    useGluetun = mkOption {
      description = ''
        Route through the gluetun VPN container's network namespace.
        Required when recyclarr's targets (sonarr/radarr) live inside
        gluetun — it reaches them at localhost:8989/7878.
      '';
      type = types.bool;
      default = false;
    };

    gluetunContainer = mkOption {
      description = "Name of the gluetun container to share netns with.";
      type = types.str;
      default = "gluetun";
    };

    networks = mkOption {
      description = "Networks to join (only used when useGluetun = false).";
      type = types.listOf types.str;
      default = ["default"];
    };

    dependsOn = mkOption {
      description = "Other oci-containers this service depends on.";
      type = types.listOf types.str;
      default = [];
      example = ["radarr" "sonarr"];
    };

    extraConfig = mkOption {
      description = "Raw YAML appended to the end of recyclarr.yml (global settings, etc.).";
      type = types.lines;
      default = "";
    };

    configProperties = mkOption {
      description = "ZFS properties applied to the baseDir dataset.";
      type = types.attrsOf types.str;
      default = {};
    };
  };

  config = mkIf cfg.enable (let
    netOpts =
      (
        if cfg.useGluetun
        then ["--network=container:${cfg.gluetunContainer}"]
        else
          ["--network-alias=recyclarr"]
          ++ (map (n: "--network=${ociLib.networkName n}") cfg.networks)
      )
      ++ imageLib.mkImageLabels {
        module = "recyclarr";
        image = cfg.image;
      };
    gluetunDeps = optional cfg.useGluetun "podman-${cfg.gluetunContainer}.service";

    # secrets.yml is a flat key→value YAML file. Recyclarr resolves
    # `!secret <key>` references in recyclarr.yml against this file.
    secretsYamlContent =
      concatStringsSep "\n" (mapAttrsToList (name: i: "${name}_api_key: ${config.sops.placeholder.${i.apiKeySecret}}")
        enabledInstances)
      + "\n";
  in {
    sops.secrets =
      listToAttrs (mapAttrsToList (_: i: nameValuePair i.apiKeySecret {}) enabledInstances);

    sops.templates."recyclarr-secrets-yml" = {
      content = secretsYamlContent;
      # World-readable through the bind mount: container runs as a
      # non-root UID and would otherwise hit EACCES on /config/secrets.yml.
      # The file still lives under /run/secrets-rendered/ which is itself
      # access-controlled.
      mode = "0444";
    };

    virtualisation.oci-containers.containers.recyclarr = {
      image = imageLib.renderImage cfg.image;
      inherit (cfg) dependsOn;
      environment = {
        "TZ" = cfg.timezone;
      };
      volumes = [
        "${cfg.baseDir}:/config"
        "${recyclarrYamlFile}:/config/recyclarr.yml:ro"
        "${config.sops.templates."recyclarr-secrets-yml".path}:/config/secrets.yml:ro"
      ];
      extraOptions =
        netOpts
        ++ [
          "--user=${toString cfg.user.uid}:${toString cfg.user.gid}"
          "--security-opt=no-new-privileges:true"
        ];
      log-driver = "journald";
    };

    systemd.services."podman-recyclarr" = ociLib.mkServiceConfig {
      networks =
        if cfg.useGluetun
        then []
        else cfg.networks;
      extraAfter = gluetunDeps;
      extraRequires = gluetunDeps;
      sopsTemplates = ["recyclarr-secrets-yml"];
    };

    modules.linux.oci._managedPaths.${cfg.baseDir}.properties = cfg.configProperties;

    modules.linux.oci.networks = mkIf (!cfg.useGluetun) (
      listToAttrs (map (n: nameValuePair n {enable = true;}) cfg.networks)
    );
  });
}
